local_costmap:
  global_frame: world
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0 #代价地图的发布频率
  transform_tolerance: 0.2 #等待坐标变换发布信息的超时时间
  always_send_full_costmap: true
  
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    track_unknown_space: false
    inf_is_valid: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      data_type: LaserScan
      topic: /scan
      marking: true
      clearing: true
      inf_is_valid: true
