shutdown_costmaps: false
planner_frequency: 5.0
planner_patience: 5.0
controller_frequency: 10.0
controller_patience: 3.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behavior_enabled: true
clearing_rotation_allowed: false

recovery_behaviors:
  - name: clear_local_costmap
    type: clear_costmap_recovery/ClearCostmapRecovery

clear_local_costmap:
  reset_distance: 3.0
  layer_names: ["obstacle_layer"]