NavfnROS:
  allow_unknown: false  #默认true，是否允许路径穿过未知区域
  default_tolerance: 0.5  #默认0.0，目标容差
  visualize_potential: false #默认false，是否显示从PointCloud2计算得到的势区域
  planner_window_x: 0.0
  planner_window_y: 0.0