TebLocalPlannerROS:

  odom_topic: odom
    
  max_vel_x: 1.0
  max_vel_x_backwards: 0.3  
  max_vel_y: 0.0
  max_vel_theta: 0.6
  acc_lim_x: 0.3
  acc_lim_theta: 0.3
  
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 3.0

  min_turning_radius: 0.0

  footprint_model:
    type: "circular"
    radius: 0.6
    is_footprint_dynamic: False
  
  xy_goal_tolerance: 0.03
  yaw_goal_tolerance: 0.01

  min_obstacle_dist: 0.3
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.0

  no_inner_iterations: 3
  no_outer_iterations: 3
  penalty_epsilon: 0.05
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 100
  weight_kinematics_forward_drive: 100
  weight_optimaltime: 1
  weight_obstacle: 50

  enable_homotopy_class_planning: false
  enable_multithreading: true
  max_number_classes: 2
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_alternative_time_cost: False
  roadmap_graph_no_samples: 5
  roadmap_graph_area_width: 1.0

  global_plan_viapoint_sep: 1.0
  weight_viapoint: 1.0
  viapoints_all_candidates: False
  selection_viapoint_cost_scale: 1.0

