common:
    lid_topic: "/livox/lidar"
    imu_topic: "/livox/imu"
    time_sync_en: false # ONLY turn on when external time synchronization is really not possible

preprocess:
    lidar_type: 1 # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
    scan_line: 4
    blind: 1.8 # 盲区距离，单位：米

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree: 360
    det_range: 15.0 # 检测范围，单位：米
    extrinsic_est_en: false # true: enable the online estimation of IMU-LiDAR extrinsic
    # 说明：
    # - 这里的外参是“IMU 与 LiDAR 之间”的相对位姿”。
    # factory_extrinsic_T: [-0.011000, -0.023290, 0.044120]
    extrinsic_T: [-0.011090, -0.024942, 0.043184]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

publish:
    path_en:  false
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame
    # 显式声明 TF frame，避免依赖默认值
    tf_imu_frame: "body_lidar"
    tf_world_frame: "world_init"

pcd_save:
    pcd_save_en: flase
    interval:
        -1 # how many LiDAR frames saved in each pcd file;
        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
feature_extract_enable: false
point_filter_num: 1
max_iteration: 3
filter_size_surf: 0.1
filter_size_map: 0.3 # 暂时未用到，代码中为0， 即倾向于将降采样后的scan中的所有点加入map
cube_side_length: 1000

ivox_grid_resolution: 0.1 # default=0.2
ivox_nearby_type: 18 # 6, 18, 26
esti_plane_threshold: 0.1 # default=0.1
